/**
 * @file	version.h
 * @author	autogenerated by radj307
 */
#pragma once
#define ckconv_VERSION_MAJOR	5
#define ckconv_VERSION_MINOR	0
#define ckconv_VERSION_PATCH	0

// Stringize function
#define VERSION_H_STRINGIZEX(x)  #x
#define VERSION_H_STRINGIZE(x)   VERSION_H_STRINGIZEX(x)

#define ckconv_VERSION VERSION_H_STRINGIZE(ckconv_VERSION_MAJOR) "." VERSION_H_STRINGIZE(ckconv_VERSION_MINOR) "." VERSION_H_STRINGIZE(ckconv_VERSION_PATCH)
