name: Linux Build

on:
  push:
    tags: '*'
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: seanmiddleditch/gha-setup-ninja@master
    
      # use apt to download gcc & g++ 10
    - run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10 zip
      shell: bash
    
    - name: Configure CMake
      run:    cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      shell:  bash
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Archive
      run:  |
            cd ${{github.workspace}}/build/ARRCON
            zip -T9 ARRCON-$(./ARRCON -vq)-Linux.zip ARRCON
      shell: bash
      
    - name: Upload Latest Artifact
      uses: actions/upload-artifact@v2
      with:
        name: latest-linux
        path: ${{github.workspace}}/build/ARRCON/*.zip
        retention-days: 2
