name: macOS Build

on:
  push:
    tags: '*'
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: Configure CMake
      run:    cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      env:
        CC:   gcc-10
        CXX:  g++-10
      
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Archive
      run:  |
            cd ${{github.workspace}}/build/ARRCON
            zip -T9 ARRCON-$(./ARRCON -vq)-macOS.zip ARRCON
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: latest-macos
        path: ${{github.workspace}}/build/ARRCON/*.zip
        retention-days: 2
